### ISSUE TITLE
FIO test failure, "fio: client localhost, timeout on cmd SEND_ETA"

### ISSUE THREAD

**Issue by ScottESanDiego** [NVIDIA/Bobber#20]
After executing tests that include `fio`, it seems that one of the IOPS tests failed:

```
dgxuser@dgxa100:~$ bobber parse-results ~dgxuser/bobber_logs/
Warning: Invalid number of results found in /home/dgxuser/bobber_logs/stg_bw_iteration_2_threads_16_direct_1_depth_16_systems_1_version_6_0_0.log log file. Skipping...
Warning: Invalid number of results found in /home/dgxuser/bobber_logs/stg_iops_iteration_1_threads_200_direct_1_systems_1_version_6_0_0.log log file. Skipping...
Warning: Invalid number of results found in /home/dgxuser/bobber_logs/stg_iops_iteration_2_threads_200_direct_1_systems_1_version_6_0_0.log log file. Skipping...
Warning: Invalid number of results found in /home/dgxuser/bobber_logs/stg_iops_iteration_2_threads_200_direct_1_systems_1_version_6_0_0.log log file. Skipping...
Systems tested: 1
Aggregate Read Bandwidth: 18.4  GB/s
Aggregate Write Bandwidth: 30.0  GB/s
Aggregate Write IOPS: 104.0 k IOPS
NCCL Max Bus Bandwidth: 230.79 at 1024.0 MB
+----------------------------+-------------+---------+
| Test                       |   1 Node(s) | Scale   |
+============================+=============+=========+
| FIO Read (GB/s) - 1MB BS   |        18.4 | N/A     |
+----------------------------+-------------+---------+
| FIO Write (GB/s) - 1MB BS  |          30 | N/A     |
+----------------------------+-------------+---------+
| FIO Read (k IOPS) - 4K BS  |           0 | N/A     |
+----------------------------+-------------+---------+
| FIO Write (k IOPS) - 4K BS |         104 | N/A     |
+----------------------------+-------------+---------+
| NCCL Max BW (GB/s)         |      230.79 | N/A     |
+----------------------------+-------------+---------+
JSON data saved to bobber_results_2021-02-11_9.53.5.json
```

Examining the log file directly, shows that one of the `fio` tests failed to run, being instead full of:
```
Jobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^Mclient <localhost>: timeout on SEND_ETA
Jobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^Mclient <localhost>: timeout on SEND_ETA
Jobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^Mclient <localhost>: timeout on SEND_ETA
Jobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^MJobs: 0 (f=0)^Mclient <localhost>: timeout on SEND_ETA
Jobs: 0 (f=0)^Mfio: client localhost, timeout on cmd SEND_ETA
```

Tarball of the logs directory attached.
(Note that I removed DALI logs that were in there from a prior run, so the tarball is "all logs except for DALI")

[bobber_logs_fio_fail.tar.gz](https://github.com/NVIDIA/Bobber/files/5967644/bobber_logs_fio_fail.tar.gz)

**Comment by roclark** [comment]
Thanks @ScottESanDiego, I will dive into the logs. Seems like there is a timeout issue with fio, but it's strange that it's seemingly only for the reads. I haven't seen this on any of our test systems, but I will try on a local DGX OS 5-based workstation and see if I get anything different there. Is this targeting the `/raid` array, or something else?

**Comment by ScottESanDiego** [comment]
Yes, this is a DGX A100 with a freshly installed DGX OS 5.0.0, output to `~/bobber_logs` and data on `/raid/bobber`.

Re-running with just the `fio` IOPs test (`bobber run-stg-iops --iterations 2 --sweep --system dgx-a100-single ~dgxuser/bobber_logs localhost`) yields occasional failures that seem similar:

```
[snip]
blocksize=4k
size=4194304k
numjobs=200
directory=/mnt/fs_under_test/fiodir.20210211182637
fio: connect: Connection timed out
fio: failed to connect to localhost:8765
Starting Drop Caches: Thu Feb 11 18:33:10 UTC 2021
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
vm.drop_caches = 3
Ending Drop Caches: Thu Feb 11 18:33:11 UTC 2021
Killing Server on localhost
Cleaning workspace
Done Running FIO Test
dgxuser@dgxa100:~$
```

Seems to work sometimes though, so not 100% repeatable. For example, another run failed in the 1st iteration, but worked in the 2nd.
```
[snip]
invalidate=1
blocksize=1024k
size=4194304k
numjobs=200
directory=/mnt/fs_under_test/fiodir.20210211184002
fio: connect: Connection timed out
fio: failed to connect to localhost:8765
Command:
/usr/bin/fio --rw=write --direct=1 --ioengine=posixaio --iodepth=16 --create_serialize=0 --fallocate=none --group_reporting=1 --disable_lat=1 --disable_clat=1 --disable_slat=1 --startdelay=5 --ramp_time=3 --runtime=180 --time_based=1 --invalidate=1 --blocksize=4k --size=4194304k --numjobs=200 --directory=/mnt/fs_under_test/fiodir.20210211184002
[iotest]
rw=write
direct=1
ioengine=posixaio
iodepth=16
create_serialize=0
fallocate=none
group_reporting=1
disable_lat=1
disable_clat=1
disable_slat=1
startdelay=5
ramp_time=3
runtime=180
time_based=1
invalidate=1
blocksize=4k
size=4194304k
numjobs=200
directory=/mnt/fs_under_test/fiodir.20210211184002
hostname=dgxa100, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.1, flags=1
<dgxa100> iotest: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=posixaio, iodepth=16
<dgxa100> ...
<dgxa100> Starting 200 processes
<dgxa100> iotest: Laying out IO file (1 file / 4096MiB)
<dgxa100> iotest: Laying out IO file (1 file / 4096MiB)
<dgxa100> iotest: Laying out IO file (1 file / 4096MiB)
[snip]
```

**Comment by roclark** [comment]
I've run a number of tests on various systems and it appears this boils down to an issue with the way Docker limits memory on dual-socket systems, such as the DGX A100. For high thread counts like the default of 200 for the fio IOPS test, a sizable chunk of memory is allocated prior to starting the tests. We limit the amount of memory in the containers to 40GB which the test never comes close to exceeding, but it appears the memory could be pinned to a specific NUMA region that Docker isn't allocating for, causing the request to go stale.

In our internal testing, we used lower thread counts, and are unable to reproduce this with 200 thread count levels on single-socket systems used in our CI and other testing and were unable to identify this. Moving forward, we intend to add dual-socket systems to our CI.

To resolve this now, I created a small patch which removes the memory limit on the Docker container, allowing all of the available system memory to be accessible. In follow-up testing, this appears to resolve the issue here.

**Comment by ScottESanDiego** [comment]
This looks great to me - in 56 runs of `bobber run-stg-iops --iterations 2 --sweep --system dgx-a100-single ~dgxuser/bobber_logs localhost` I saw no failures.

**Comment by roclark** [comment]
Thanks for following up! I included the patch with our next release so once it and all other updates get signed off I will cut another release so this can be reflected in a new binary.
