### ISSUE TITLE
Update wheel version referenced in doc

### ISSUE THREAD

**Issue by joehandzik** [NVIDIA/Bobber#35]
Either we need to generalize the readme, or we need to update the README when releases get cut. Currently, Wheel version 6.0.0 is referenced, rather than the current 6.1.0.

**Comment by roclark** [comment]
Possibly easiest to just update the README when releases get cut? Also, once the package becomes available on the package index, we can remove hard-links to packages hosted on GitHub which would remove another version in the README. I can get in the habit of updating the README with new package updates.
