### ISSUE TITLE
Support non-DGX platforms

### ISSUE THREAD

**Issue by roclark** [NVIDIA/Bobber#7]
In an effort to make this tool more accessible to non-DGX platforms, steps should be included for systems that don't have pre-tuned configs. This could mean adding a `generic` system profile which has several default configs that can be used for testing on a workstation-sized system and requiring the user to add their GPU count, and also allowing a path for contributors to submit a pre-tuned config for a system that isn't already supported. Whichever route(s) is/are chosen, it should be well documented to give users an idea of how to run on a system that isn't already supported.

**Comment by joehandzik** [comment]
I would say that "generic" is equivalent to not specifying a system type at all, and manually specifying things like GPU count, network devices, etc. We should make sure that those paths are all supported (for example, not sure you can specify your own mlx5_# values), and consider documenting how someone would figure out what should go there (example: run ibdev2netdev, and choose the device names that match compute network interfaces - noting that they must be the same across all hosts in the test group).

**Comment by roclark** [comment]
Looking into this now and thought of something. Do we want to add the ability for users to test against non-uniform GPU counts for multi-systems? Probably not, but wondering if we should think about a hypothetical cluster that has both DGX A100s and DGX-2s? Or perhaps an even bigger mismatch of non-DGX equipment. In theory, we could do something similar to what `mpirun` does to specify the number of processes per host by allowing users to add the GPU count after each host:

```
bobber run-all ... dgx-a100-1:8,dgx-a100-2:8,dgx-2:16
```

The NCCL tests would probably be difficult to get the `mlx5_n` values correct between different system types, but just a thought.
